# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

  # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Restore NuGet packages
      - uses: nuget/setup-nuget@v1
      - name: Restore NuGet packages
        run: nuget restore Nirvana.sln
        
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: x64 Debug
        run: ./BuildAndTest.ps1 "x64" "Debug 2022"
        shell: pwsh

      - name: x64 Release
        run: ./BuildAndTest.ps1 "x64" "Release 2022"
        shell: pwsh

      - name: Win32 Debug
        run: ./BuildAndTest.ps1 "Win32" "Debug 2022"
        shell: pwsh

      - name: Win32 Release
        run: ./BuildAndTest.ps1 "Win32" "Release 2022"
        shell: pwsh

      - name: x64 Debug LLVM
        run: ./BuildAndTest.ps1 "x64" "Debug LLVM"
        shell: pwsh

      - name: x64 Release LLVM
        run: ./BuildAndTest.ps1 "x64" "Release LLVM"
        shell: pwsh
        
      - name: List Tests
        run: dir test-results
        shell: cmd

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
            python-version: 3.8

      - name: Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        id: test-results
        if: always()
        with:
            junit_files: "test-results/**/*.xml"

      - name: Set badge color
        shell: bash
        run: |
          case ${{ fromJSON( steps.test-results.outputs.json ).conclusion }} in
            success)
              echo "BADGE_COLOR=31c653" >> $GITHUB_ENV
              ;;
            failure)
              echo "BADGE_COLOR=800000" >> $GITHUB_ENV
              ;;
            neutral)
              echo "BADGE_COLOR=696969" >> $GITHUB_ENV
              ;;
          esac

      - name: Create badge
        uses: emibcn/badge-action@v2.0.2
        with:
          label: Tests
          status: '${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.tests }} tests, ${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.runs }} runs: ${{ fromJSON( steps.test-results.outputs.json ).conclusion }}'
          color: ${{ env.BADGE_COLOR }}
          path: badge.svg

      - name: Upload badge to Gist
        # Upload only for master branch
        if: >
          github.event_name == 'workflow_run' && github.event.workflow_run.head_branch == 'master' ||
          github.event_name != 'workflow_run' && github.ref == 'refs/heads/master'
        uses: andymckay/append-gist-action@1fbfbbce708a39bd45846f0955ed5521f2099c6d
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gistURL: https://gist.githubusercontent.com/silver-popov/5e83ddfb2531206b60b6451851c51b2a
          file: badge.svg
